### PR TITLE
updated climex notebook

### PR DESCRIPTION
**Pull request by tlogan2000**
This PR updates the climex notebook to take advantage of improved thredds performance.

The analysis is much more complete.. .  accessing all realizations, over the entire domain, in the first climate indicator example. 
The second example (point over mtl) accesses all years for all realizations

 @tlvu these changes might be too 'intense' for Jenkins runs?

### CODE REVIEW

**Comment by tlogan2000** [comment]
<p>If I understand correctly I believe that as the data on disk is chunked  50x50 spatially it makes no real difference in terms of amount of data streamed from THREDDS.   xarray / clisops subsetting subsequently removes unneeded grid points so there is never very much RAM being used but thredds technically will deliver it all (even if dask chunks are set smaller).      </p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tlogan2000** [comment]
<p>Updating to mean, max, min with standard color scale</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tlogan2000** [comment]
<p>Changing text slightly &amp; will try 25x25 .</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tlogan2000** [comment]
<p>I think I will simply remove my timer in both cases.  This is tailor made to break Jenkins runs</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tlogan2000** [comment]
<p>removing to avoid breaking jenkins... progress available in dashboard now </p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tlogan2000** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by huard — APPROVED** [review]

**Comment by tlogan2000** [comment]
@tlvu has your ticket for increased RAM on Jenkins been addressed?  Will wait to merge until you give the ok

**Comment by tlvu** [comment]
> @tlvu has your ticket for increased RAM on Jenkins been addressed? Will wait to merge until you give the ok

@tlogan2000 No return from HelpOX, will have to ping the again.

**Pull request merged**
