### PR TITLE
Regridding Notebook with xESMF

### LINKED ISSUE #192: Document usage of regridding methods
Notebooks on
- [x] Regridding with xESMF
- [x] Spatial average over polygons taken from GeoServer
- [x] Reusing weights

### PR DESCRIPTION
**Pull request by aulemahal**
Fixes #192  

This notebook shows the following examples:

 - [x] Simple regridding (basic xESMF how-to, irregular to regular grid, bilinear, increasing resolution)
 - [x] Conservative regridding (computing grid corners from bounds with cf_xarray)
 - [x] Regridding with masks (adding mask variables, mask related issues, decreasing resolution)

I plan to add:

 - [x] Averaging over polygons

### CODE REVIEW

**Comment by aulemahal** [comment]
`xESMF` is missing from pavics currently, so the first cell pip-installs it to the user directory.

@huard You said xclim-testdata's are accessible through thredds? I'm not sure where, so it currently uses xclim's `open_dataset` instead. Not a big deal, but would be cool to use thredds.

**Comment by huard** [comment]
My mistake, we did that for raven and I thought we had done it already for xclim. 

@tlvu Could you
- [ ] sync xclim-testdata on THREDDS in the testdata directory (same as with raven-testdata)
- [ ] add xesmf to the jupyterlab environment

**Comment by tlvu** [comment]
@huard 

> * [ ]  sync xclim-testdata on THREDDS in the testdata directory (same as with raven-testdata)

On this, `/testdata/xclim`, next to `/testdata/raven` ?

>  * [ ] add xesmf to the jupyterlab environment

I explicitly add this to the Jupyter env or this will become a dependency of xclim and will be pulled into the Jupyter env by the next version of xclim?

**Comment by aulemahal** [comment]
I don't think it will ever become an explicit dependency of xclim. It may become a dependency of clisops, which is maybe already in the env? 
Nonetheless, I think we want xESMF in itself, explictely.

**Comment by huard** [comment]
@tlvu 
Yes.
Agree with Pascal.

**Comment by tlvu** [comment]
Why the default branch of xclim-testdata is main but raven-testdata is master? !

**Comment by aulemahal** [comment]
Github's "Black Lives Matter" move in the time in between...

**Comment by huard** [comment]
Pas oublier d'inclure le notebook dans index.

**Comment by aulemahal** [comment]
@huard There it is! With an additional example about averaging over shapes and extra stuff for reusing weights.

**Review by huard — APPROVED** [review]

**Comment by huard** [comment]
Really nice ! Please review my changes and merge when you are comfortable.

**Pull request merged**
