### PR TITLE
Notebook showcasing the ECCC geoapi 

### PR DESCRIPTION
**Pull request by huard**
Access to daily station data, conversion to xr.Dataset and computation of climate indicators using the WMO missing values option. 

Note: requires the latest cf-xarray (0.6.3).

### CODE REVIEW

**Review by aulemahal — APPROVED** [review]
Nice! Your function here is pretty much what I need to implement in finch.

**Comment by huard** [comment]
Waiting for https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95 to merge.

**Comment by tlogan2000** [comment]
@huard made a few comments on the reviewnb app.  Not sure if you are getting notifications for my comments?

**Comment by tlogan2000** [comment]
> @huard made a few comments on the reviewnb app. Not sure if you are getting notifications for my comments?

Quick summary:
```
Line #1.    import cf_xarray as cfxr
NB The production "current" docker image has cf_xarray 0.6.1 but need >=0.6.2 for new cfxr.geometry functions.
```
```
Line #50.                name = key.removesuffix("_FLAG")
removesuffx() not available on pavics jupyter. This is a python 3.9 feature but I'm not sure what runs on the prod server
Continuing review but replaced personal version with key.replace("_FLAG","")
```

**Comment by huard** [comment]
Yep, got it, thanks! 

Won't merge PR until new env with recent cf-xr is included. 

Will use key.replace

**Comment by tlogan2000** [comment]
> Yep, got it, thanks!
> 
> Won't merge PR until new env with recent cf-xr is included.
> 
> Will use key.replace

Great looks good to me once these small changes are taken care of

**Review by tlogan2000 — APPROVED** [review]

**Comment by tlvu** [comment]
> Line #50.                name = key.removesuffix("_FLAG")
> removesuffx() not available on pavics jupyter. This is a python 3.9 feature but I'm not sure what runs on the prod server

FYI, the upcoming Jupyter env rebuild in https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95 will have python 3.9.

**Comment by tlvu** [comment]
Something funny with ReviewNB, I don't see any comments there.

**Pull request merged**
