### PR TITLE
Notebook extensions

### PR DESCRIPTION
**Pull request by ChaamC**
Documentation for the new jupyterlab extensions we are adding
This notebook will give easily accessable documentation for the user, and will give an overview of what he can do with the extensions.

Matching PR Ouranosinc/PAVICS-e2e-workflow-tests#54 for the new image with 4 new extensions: jupytext, jupyterlab-google-drive, jupyter_conda and jupyterlab-git

Matching PR bird-house/birdhouse-deploy#97 for jupyterlab-google-drive deployment config.

### CODE REVIEW

**Review by dbyrns — APPROVED** [review]

**Comment by tlvu** [comment]
Adding DavidH and Travis as this new notebook will be automatically deployed as tutorial notebooks on Jupyter once this PR is merged.  I looks good to me so far.  Wonder what you guys think.  

It would be cool if CRIM can provide an deployed Jupyter env so we can follow the instructions and try it out.

**Comment by tlvu** [comment]
Related PR https://github.com/bird-house/birdhouse-deploy/pull/97, https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/54.

**Review by huard — APPROVED** [review]

**Review by MatProv — APPROVED** [review]

**Comment by ChaamC** [comment]
> It would be cool if CRIM can provide an deployed Jupyter env so we can follow the instructions and try it out.

I think @MatProv is working on this, we'll get back to you!

**Comment by tlvu** [comment]
@ChaamC all merged, thanks for your 3 PR.  Sorry took some time to try them out since I will need to provide support if someone has questions.

**Pull request merged**
