### PR TITLE
update thredds access notebook with magpie-auth active

### PR DESCRIPTION
**Pull request by fmigneault**
Following up on comment identified by @tlvu 

https://github.com/bird-house/birdhouse-deploy/pull/107#issuecomment-803167923

NB. error will not actually raise until https://github.com/bird-house/birdhouse-deploy/pull/107 is integrated

preview: 
https://github.com/Ouranosinc/pavics-sdi/blob/magpie-unauthorized-thredds/docs/source/notebooks/pavics_thredds.ipynb

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Review by tlvu — APPROVED** [review]
LGTM

**Comment by tlvu** [comment]
I am guessing this notebook will break without bird-house/birdhouse-deploy#107 so you'll need to sync the merge of this PR with bird-house/birdhouse-deploy#107 ?

**Comment by fmigneault** [comment]
> I am guessing this notebook will break without [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107) so you'll need to sync the merge of this PR with [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107) ?

@tlvu 
Yes. Indeed, there are about 4 PR pending related to enabling magpie, and I'm starting to loose track of which one is which.

**Comment by tlvu** [comment]
> Yes. Indeed, there are about 4 PR pending related to enabling magpie, and I'm starting to loose track of which one is which.

Yes indeed, another reason to not fall behind magpie next time.

**Pull request merged**
