### PR TITLE
notebooks: new birdy 0.7.0 has a new output_formats option and new NumPy np.bool deprecation warning

### PR DESCRIPTION
**Pull request by tlvu**
From new Jupyter env in https://github.com/bird-house/birdhouse-deploy/pull/121.

New birdy client `output_formats` option is probably from this PR https://github.com/bird-house/birdy/pull/182.

### CODE REVIEW

**Review by huard — APPROVED** [review]
Are the deprecation warnings on our end ? Otherwise could we silence them ?

**Comment by tlvu** [comment]
> Are the deprecation warnings on our end ? Otherwise could we silence them ?

Not on our end, I think we pulled a new numpy (like we pulled a new birdy) with the latest Jupyter env rebuild.

It's the kind of warnings that appears on first run only.  But during Jenkins run, everything is "fresh" so we get it.

**Comment by tlvu** [comment]
> It's the kind of warnings that appears on first run only. But during Jenkins run, everything is "fresh" so we get it.

Opps sorry the warnings do not go away on a second run.  There do not seem to have a way to disable that specific deprecation warnings from the docs https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by tlvu** [comment]
The lines that trigger the warnings are:
```
lat = D.variables['lat'][:]
lon = D.variables['lon'][:]
print(time.units, time[0], nc.num2date(time[0], time.units))
```

And `D` is from:
```
import netCDF4 as nc
D = nc.Dataset(url)
```

So I think the fix is on `netCDF4` side.

**Comment by huard** [comment]
`warnings.filterwarnings("ignore", category=DeprecationWarning)`

**Comment by tlvu** [comment]
> `warnings.filterwarnings("ignore", category=DeprecationWarning)`

https://github.com/Ouranosinc/pavics-sdi/pull/199

**Pull request merged**
