### PR TITLE
Trying to subset using finch but error on server

### PR DESCRIPTION
**Pull request by huard**
Started to write a notebook calling finch.subset_gridpoint, but it fails when I try it on pavics.ouranos.ca. Works fine locally... stumped.

### CODE REVIEW

**Comment by tlvu** [comment]
Is Finch on pavics old?  It has not been updated since May around the launch of the climate site thingy.

**Comment by huard** [comment]
That's very possible. Lots of fixes since then. Worth a try. I've added a very basic notebook example on jupyterlab in david/Finch_subset

**Comment by huard** [comment]
Hum, I'm running 0.2.4, the same version in the deployment, so it's something else.

**Comment by tlvu** [comment]
Cool to provide a way to reproduce it on our Jupyter.

I get this error on Finch server side:

```
INFO:PYWPS:Processing started
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pavics.ouranos.ca:443
DEBUG:urllib3.connectionpool:https://pavics.ouranos.ca:443 "GET /twitcher/ows/proxy/thredds/dodsC/birdhouse/cmip5/MRI/rcp85/fx/atmos/r0i0p0/sftlf/sftlf_fx_MRI-CGCM3_rcp85_r0i0p0.nc.dds HTTP/1.1" 200 None
INFO:PYWPS:Opened dataset as an OPeNDAP url: https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/cmip5/MRI/rcp85/fx/atmos/r0i0p0/sftlf/sftlf_fx_MRI-CGCM3_rcp85_r0i0p0.nc
INFO:PYWPS:Processing file 1 of 2
Traceback (most recent call last):
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/pywps/app/Process.py", line 208, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/code/finch/processes/base.py", line 29, in _handler_wrapped
    return self.old_handler(request, response)
  File "/code/finch/processes/wps_xsubsetpoint.py", line 140, in _handler
    metalink = self.subset(request.inputs, response)
  File "/code/finch/processes/wps_xsubsetpoint.py", line 133, in subset
    metalink = self.subset_resources(wps_inputs["resource"], _subset_function, threads=threads)
  File "/code/finch/processes/subset.py", line 50, in subset_resources
    process_resource(r)
  File "/code/finch/processes/subset.py", line 27, in process_resource
    out = subset_function(ds)
  File "/code/finch/processes/wps_xsubsetpoint.py", line 131, in _subset_function
    return subset_gridpoint(dataset, lon=lon, lat=lat, start_yr=y0, end_yr=y1)
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xclim/subset.py", line 137, in subset_gridpoint
    out = da.isel(**args)
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xarray/core/dataset.py", line 1642, in isel
    name, var, self.indexes[name], var_indexers)
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xarray/core/indexes.py", line 77, in isel_variable_and_index
    new_variable = variable.isel(indexers)
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xarray/core/variable.py", line 927, in isel
    return self[tuple(key)]
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xarray/core/variable.py", line 636, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/xarray/core/indexing.py", line 1261, in __getitem__
    result = self.array[key]
  File "/opt/conda/envs/finch/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3958, in __getitem__
    return getitem(key)
IndexError: index 253 is out of bounds for axis 0 with size 160
ERROR:PYWPS:Process error: method=wps_xsubsetpoint.py._handler, line=140, msg=index 253 is out of bounds for axis 0 with size 160
```

**Comment by Zeitsperre** [comment]
Can confirm here that it isn't due to the xclim version. See https://github.com/Ouranosinc/xclim/issues/190.

**Comment by tlvu** [comment]
What else needs to be done to close this?  Finch and Flyingpigeon should be fully operational on Pavics now, Jenkins been green for a few days.

**Comment by huard** [comment]
Seems to work now. closing.

**Pull request closed without merging**
