### PR TITLE
notebooks: fix output change breaking Jenkins due to new Jupyter env

### PR DESCRIPTION
**Pull request by tlvu**
New Jupyter env https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/68.

Passing Jenkins build with this fix http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-clisops-and-add-xkcd-font-for-matplotlib/16/console

See each commit for the fixed output detected by Jenkins.

Migrate to Xarray html output with NBVAL_IGNORE_OUTPUT to avoid breaking Jenkins (html output always detected as different by nbval).

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Review by aulemahal — APPROVED** [review]
Simply an update of cf-xarray, nothing different for the user's comprehension!

**Comment by tlvu** [comment]
> Simply an update of cf-xarray, nothing different for the user's comprehension!

Thanks for the clarification.  So I'll add `# NBVAL_IGNORE_OUTPUT` to ignore output change for that cell in the future.

**Comment by tlvu** [comment]
@aulemahal I have a new output change with regridding.ipynb, see 9937bc3c9ff999a7b939092003de33637e36ecaa.

This is probably due to a full build of the Jupyter env which also pull in the latest xarray.  Is that change due to xarray?  Is it normal that the Longitude value changed slightly?

**Comment by tlvu** [comment]
> Oh that's weird. Something somewhere slightly changed the position of the text label... We can avoid the output with a ";", commit in a sec.

@aulemahal thanks!  I didn't realized it's the position of the label, I thought it was the value of the label!  Merged.

**Pull request merged**
