### PR TITLE
Add climex notebook

### LINKED ISSUE #9: Create CLIMEX analysis workflow
Write and test a workflow analyzing the CLIMEX ensemble.

### PR DESCRIPTION
**Pull request by huard**
Add notebook showing how to access climex dataset from our NcML catalog, create maps and compute indicators. There are significant performance issues affecting the notebook. Extracting a time series over 150 years for the 50 members would probably take days. 

Fixes #9

### CODE REVIEW

**Comment by tlvu** [comment]
Tried the new notebook on Jenkins, 2 errors: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1335/console

I think this one you need `# NBVAL_IGNORE_OUTPUT` due to the time to complete that will vary on each run.
```
17:28:02  _________ pavics-sdi-fix-9/docs/source/notebooks/climex.ipynb::Cell 3 __________
17:28:02  Notebook cell execution failed
17:28:02  Cell 3: Cell outputs differ
17:28:02  
17:28:02  Input:
17:28:02  from matplotlib import pyplot as plt
17:28:02  with ProgressBar():
17:28:02      field = ds.tas.isel(time=0, realization=0).load()
17:28:02      field.plot()
17:28:02  
17:28:02  Traceback:
17:28:02   mismatch 'stdout'
17:28:02  
17:28:02   assert reference_output == test_output failed:
17:28:02  
17:28:02    '[###########...one |  1.0s\n' == '[###########...ted | 16.7s\n'
17:28:02    Skipping 51 identical leading characters in diff, use -v to show
17:28:02    - ompleted | 16.7s
17:28:02    + ompleted |100% Done |  1.0s
17:28:02  
```

This one not sure why, maybe a "Restart kernel and run all cells" might help.
```
17:28:02  _________ pavics-sdi-fix-9/docs/source/notebooks/climex.ipynb::Cell 4 __________
17:28:02  Notebook cell execution failed
17:28:02  Cell 4: Cell outputs differ
17:28:02  
17:28:02  Input:
17:28:02  import cartopy.crs as ccrs
17:28:02  with ProgressBar():
17:28:02      # The CRS for the rotated pole (data)
17:28:02      rotp = ccrs.RotatedPole(pole_longitude=ds.rotated_pole.grid_north_pole_longitude, 
17:28:02                             pole_latitude=ds.rotated_pole.grid_north_pole_latitude)
17:28:02  
17:28:02      # The CRS for your map projection (can be anything)
17:28:02      ortho = ccrs.Orthographic(central_longitude=-80, central_latitude=45)
17:28:02  
17:28:02      fig = plt.figure(figsize=(8, 4))
17:28:02  
17:28:02      # Plot data on the rotated pole projection directly
17:28:02      ax = plt.subplot(1, 2, 1, projection=rotp)
17:28:02      ax.coastlines()
17:28:02      ax.gridlines()
17:28:02      m = ax.pcolormesh(ds.rlon, ds.rlat, field)
17:28:02      plt.colorbar(m, orientation='horizontal', label=field.long_name, fraction=0.046, pad=0.04)
17:28:02  
17:28:02      # Plot data on another projection, transforming it using the rotp crs. 
17:28:02      ax = plt.subplot(1, 2, 2, projection=ortho)
17:28:02      ax.coastlines()
17:28:02      ax.gridlines()
17:28:02      m = ax.pcolormesh(ds.rlon, ds.rlat, field, transform=rotp)  # Note the transform parameter
17:28:02      plt.colorbar(m, orientation='horizontal', label=field.long_name, fraction=0.046, pad=0.04)
17:28:02  
17:28:02      plt.show()
17:28:02  
17:28:02  Traceback:
17:28:02  Unexpected output fields from running code: {'stderr'}
```

**Comment by tlvu** [comment]
Jenkins passed for new notebook http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1337/console

**Review by tlogan2000 — APPROVED** [review]
This looks good to me. I found once small typ noted in NbReview app. 

Other than that I think the Climex data should be the first to be transferred to the new SSD drives.  I'm very curious so to see how performance will be improved

**Comment by huard** [comment]
I don't see your comments in the nbreview app, but fixed 3 typos. 
I'm skeptical that slow access is predominantly due to disks. That is, I'm sure it will improve speed, but I suspect our NcML construction is sub-optimal.

**Pull request merged**
