### PR TITLE
Added nb accessing GEPS forecasts and computing xclim indicators

### PR DESCRIPTION
**Pull request by huard**
A new notebook showing how to access forecast data and running indicator computations. 

@tlvu All the cells are going to produce different results every day (because the forecast is the most recent one issued by ECCC). 
Should I put NBVAL comments inside each cell or you're going to white list it on your end? We want to know if there is an error, but not compare the cell outputs. 

Fixes https://github.com/Ouranosinc/xclim/issues/773

### CODE REVIEW

**Review by tlvu — CHANGES_REQUESTED** [review]
Some minor changes needed to make it pass Jenkins.

**Comment by huard** [comment]
<p>ok</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/242/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by huard** [comment]
<p>Weird, I think I committed an earlier version, cause I got rid of those. </p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/242/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by huard** [comment]
@tlvu 
- Added the #NBVAL_IGNORE_OUTPUT
- Refreshed the nb and confirmed the RtB build has no warnings and displays the last graphic.

**Review by tlvu — APPROVED** [review]
Jenkins passed http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1405/console, merge when ready.

**Pull request merged**
