### PR TITLE
WCS_example.ipynb: fix output change breaking Jenkins

### PR DESCRIPTION
**Pull request by tlvu**
Note the new graph looks every different than the previous one, is that expected?

Screenshot from 2021-02-16 12-08-32

Fix following change:

```
  ______ pavics-sdi-master/docs/source/notebooks/WCS_example.ipynb::Cell 5 _______
  Notebook cell execution failed
  Cell 5: Cell outputs differ

  Input:
  ds = xr.open_dataset(fn)
  print(ds.data_vars)
  ds.Band1.plot()
  plt.show()

  Traceback:
   mismatch 'stdout'

   assert reference_output == test_output failed:

    'Data variabl...float32 ...\n' == 'Data variabl...float32 ...\n'
      Data variables:
    +     crs      |S1 ...
          Band1    (lat, lon) float32 ...
```

### CODE REVIEW

**Comment by huard** [comment]
Je  ne sais pas... possiblement dû à un changement aux valeurs manquantes.

**Comment by Zeitsperre** [comment]
Yeah, that looks like a change in the data or a GDAL-based library. I can look into this eventually.

**Comment by tlvu** [comment]
In the mean time, can merge this to fix Jenkins?  Can open a new issue to track the graph change so this do not fall between the cracks.

@huard Had we enable `--nbval-lax` we would not have caught this.  Whether this error was worth catching is outside of my knowledge zone.

**Comment by huard** [comment]
Yes, please merge, and no, let's not divert attention. This is just an example of a WCS process.

**Pull request merged**
