### PR TITLE
small differences in outputs with new build

### PR DESCRIPTION
**Pull request by tlogan2000**
This is most likely due to to xarray being upgraded to 0.14.x (?).  Very minor but causes jenkins failures
when testing https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/add-threddsclient-bokeh-to-jupyter-env

### CODE REVIEW

**Comment by tlvu** [comment]
+1, Jenkins pass now.  Just have the Finch repo to fix.

**Comment by tlogan2000** [comment]
@huard do failing checks need to be addressed before merging this?  I imagine this is not a huge deal...

**Comment by huard** [comment]
So the import errors should ideally be fixed. Might mean that the environment has a conflict in it. 

The other error is probably related to our weird GeoServer issue where boundaries seem to vary over time. @tlvu I don't think we've diagnosed the source of this yet, correct ?

**Comment by tlvu** [comment]
> The other error is probably related to our weird GeoServer issue where boundaries seem to vary over time. @tlvu I don't think we've diagnosed the source of this yet, correct ?

Nope unfortunately.  I don't think someone is screwing around on the server so this is a software random buggy error.

**Comment by tlvu** [comment]
All good on Jenkins http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/add-threddsclient-bokeh-to-jupyter-env/6/console, this PR can be merged.

**Pull request merged**
