### PR TITLE
subset-user-input.ipynb: fix output for Thredds v5

### PR DESCRIPTION
**Pull request by tlvu**
Only merge if https://github.com/bird-house/birdhouse-deploy/pull/413 can be merged.

This is mostly to have a nice notebook diff.

```
15:47:13  ___ pavics-sdi-master/docs/source/notebooks/subset-user-input.ipynb::Cell 12 ___
15:47:13  Notebook cell execution failed
15:47:13  Cell 12: Cell outputs differ
15:47:13  
15:47:13  Input:
15:47:13  # gather data from the PAVICS data catalogue
15:47:13  catalog = "https://boreas.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/gridded_obs/catalog.xml"  # TEST_USE_PROD_DATA
15:47:13  
15:47:13  cat = TDSCatalog(catalog)
15:47:13  data = cat.datasets[0].access_urls["OPENDAP"]
15:47:13  data
15:47:13  
15:47:13  Traceback:
15:47:13   mismatch 'text/plain'
15:47:13  
15:47:13   assert reference_output == test_output failed:
15:47:13  
15:47:13    "'https://pav...rcan_v2.ncml/'" == "'https://pav...s/nrcan.ncml'"
15:47:13    Skipping 70 identical leading characters in diff, use -v to show
15:47:13    - _obs/nrcan.ncml'
15:47:13    + _obs/nrcan_v2.ncml'
15:47:13    ?           +++
15:47:13
```

### CODE REVIEW

**Comment by tlvu** [comment]
@tlogan2000 is `nrcan_v2.ncml` and `nrcan.ncml` equivalent?

**Comment by tlogan2000** [comment]
> @tlogan2000 is `nrcan_v2.ncml` and `nrcan.ncml` equivalent?

It's not the same data no

**Comment by tlvu** [comment]
> > @tlogan2000 is `nrcan_v2.ncml` and `nrcan.ncml` equivalent?
> 
> It's not the same data no

So it is not expected that with the new Thredds v5, `nrcan_v2.ncml` is used instead of `nrcan.ncml`?

**Comment by tlogan2000** [comment]
@tvlu THREDDS sorting of datasets seems to have changed between v4 and v5.   Two options to fix.

1) Leave as is and accept that THREDDS v5 finds nrcan_v1 in the `[0]` index of the catalogue search.  The example is still valid in terms of operations (subsetting and calculations etc etc)

or 

2) changing the line
```
data = cat.datasets[0].access_urls["OPENDAP"]
``` 
to 
```
data = cat.datasets[-1].access_urls["OPENDAP"]
```
should ensure that v2 is found instead of v1

**Comment by tlogan2000** [comment]
> Is there an access by name instead of by index

Nothing built in but I change the code to search for `nrcan_v2` should be future proof now

**Comment by tlvu** [comment]
Opps, closed by mistake.

**Comment by tlvu** [comment]
Replace by https://github.com/Ouranosinc/pavics-sdi/pull/342

**Pull request closed without merging**
