### PR TITLE
Example notebook for user input bbox and wms

### PR DESCRIPTION
**Pull request by davidcaron**
I don't plan to have this PR merged as is, but I mostly want to show the results of a couple experiments, after our discussion with @huard. Eventually, we could split these in cleaner examples.

Did you know about the ipyleaflet library? I found it really useful to interact on a map in the context of jupyter notebooks. https://ipyleaflet.readthedocs.org

So this notebook shows examples for:

 - Getting a geometry from the user (draw on a map, and get the result as a geojson)
 - Subsetting with finch using these geometries, and launching a heat wave analysis
 - Displaying WMS data in ipyleaflet (if the results of the computations were made available to thredds, we could show the results to the user without them having to download it)

### CODE REVIEW

**Comment by huard** [comment]
Nice! 

Here Colibri seems to hang. Maybe I have no access to this port ? 

On PAVICS, process outputs are saved on thredds in https://pavics.ouranos.ca/thredds/catalog/birdhouse/wps_outputs/catalog.html

**Comment by huard** [comment]
@davidcaron I'd like to include this among our notebooks as a recipe. Is this the latest version ?

**Comment by davidcaron** [comment]
I updated to the version used for the video I created for the presentation.

About colibri, it should be accessible now, but I haven't tested it yet. The twitcher and magpie update will soon be merged in pavics master and I'll update and test colibri then.

**Comment by huard** [comment]
@tlogan2000 This is the nb you're looking for.

**Comment by Zeitsperre** [comment]
@tlvu Can you verify that this notebook is running on internal infra? If so, we can merge and call it done.

**Comment by tlvu** [comment]
> @tlvu Can you verify that this notebook is running on internal infra? If so, we can merge and call it done.

@Zeitsperre New notebook works on our nightly Jenkins http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1175/console

**Review by tlvu — APPROVED** [review]
LGTM

**Pull request merged**
