### PR TITLE
remove deprecated wps providers (attempt 2)

### PR DESCRIPTION
**Pull request by mishaschwartz**
This is an addition to #292. 

I had mistakenly assumed that notebook outputs would be re-generated if the inputs were updated but since that is not the case, this makes the relevant changes to the output cells as well.

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
LGTM

**Comment by mishaschwartz** [comment]
@tlvu just checking in on this. I don't have permission to merge changes to this repo if you're waiting on me.

**Comment by tlvu** [comment]
> @tlvu just checking in on this. I don't have permission to merge changes to this repo if you're waiting on me.

Added you as collaborator to this repo.

If you need more write access to other repos, please do not hesitate.

**Comment by mishaschwartz** [comment]
@tlvu Can I just merge this or are there additional procedures for this repo before I merge?

**Comment by tlvu** [comment]
> @tlvu Can I just merge this or are there additional procedures for this repo before I merge?

Run a Jenkins specifying the branch in this PR.

If my understanding of Weaver is right, you can only merge this PR when the Mallefow are actually disabled from the stack.  Otherwise this Weaver nb will start failing in all the Pipeline.

**Comment by mishaschwartz** [comment]
@tlvu 

> If my understanding of Weaver is right, you can only merge this PR when the Mallefow are actually disabled from the stack. Otherwise this Weaver nb will start failing in all the Pipeline.

Ok but then #292 shouldn't have been merged. Should we revert #292 and wait to re-implement it when https://github.com/bird-house/birdhouse-deploy/pull/311 is merged?

**Comment by tlvu** [comment]
> @tlvu
> 
> > If my understanding of Weaver is right, you can only merge this PR when the Mallefow are actually disabled from the stack. Otherwise this Weaver nb will start failing in all the Pipeline.
> 
> Ok but then #292 shouldn't have been merged. Should we revert #292 and wait to re-implement it when [bird-house/birdhouse-deploy#311](https://github.com/bird-house/birdhouse-deploy/pull/311) is merged?

Woops !  Is that why Weaver tests are failing now in the pipeline?

How about we do the reverse, we prioritize merging #311?  What's blocking it?

I'd say if we can merge #311 within 2-3 weeks, forget about reverting #292.

In the past, Weaver have been failing for months in the pipeline simply because the notebooks was not up-to-date so I think this is not a big deal.

**Comment by mishaschwartz** [comment]
@tlvu 

> What's blocking it?

Just waiting for a final review from @fmigneault

**Review by fmigneault — APPROVED** [review]

**Comment by mishaschwartz** [comment]
Thanks for approving this one @fmigneault.

In this comment:

>> What's blocking it?

> Just waiting for a final review from @fmigneault

I was actually referring to your review for this PR: https://github.com/bird-house/birdhouse-deploy/pull/311 if you don't mind having another look at that one when you have a minute.

**Comment by huard** [comment]
Is this good to go ?

**Pull request merged**
